services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HF_TOKEN=${HF_TOKEN}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/ac215-datadetox-service.json
    ports:
      - "8080:8000"
    volumes:
      - ./backend:/app
      - ${HOST_KEY_FILE_PATH}:/app/ac215-datadetox-service.json
    tty: true
    restart: unless-stopped
    networks:
      - datadetox-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8080
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - datadetox-network

  rag_cli:
    build: 
      context: ./rag
      dockerfile: Dockerfile
    volumes:
      - ./rag:/app
      - ./data/model_doc:/app/data/model_doc
    depends_on:
      - chromadb
    environment:
      - HF_TOKEN
    restart: unless-stopped
    networks:
      - datadetox-network
    tty: true
    stdin_open: true

  chromadb:
    image: chromadb/chroma:latest
    ports:
        - 8000:8000
    volumes:
        - ./data/chromadb:/chroma/chroma
    environment:
        - IS_PERSISTENT=TRUE
        - ANONYMIZED_TELEMETRY=FALSE
        - CHROMA_CORS_ALLOW_ORIGINS=["*"] # This is not recommended for production environments.
    networks:
      - datadetox-network

networks:
  datadetox-network:
    driver: bridge 