services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY
      # - VECTOR_STORE_ID
    ports:
      # - "8000:8000"
      - "8080:8080"
    volumes:
      - ./backend:/app
    tty: true
    restart: unless-stopped
    networks:
      - datadetox-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - datadetox-network

  rag_cli:
    build: 
      context: ./rag
      dockerfile: Dockerfile
    volumes:
      - ./rag:/app
      - ./data/model_doc:/app/data/model_doc
    depends_on:
      - chromadb
    environment:
      - HF_TOKEN
    restart: unless-stopped
    networks:
      - datadetox-network
    tty: true
    stdin_open: true

  chromadb:
    image: chromadb/chroma:latest
    ports:
        - 8000:8000
    volumes:
        - ./data/chromadb:/chroma/chroma
    environment:
        - IS_PERSISTENT=TRUE
        - ANONYMIZED_TELEMETRY=FALSE
        - CHROMA_CORS_ALLOW_ORIGINS=["*"] # This is not recommended for production environments.
    networks:
      - datadetox-network

networks:
  datadetox-network:
    driver: bridge 