[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.118.3",
    "ruff>=0.14.0",
    "pydantic==2.10.0",
    "openai==2.3.0",
    "fastmcp==2.12.4", 
    "huggingface-hub==0.35.3",
]
